# Generated by Django 5.2.1 on 2025-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default='rafa', max_length=100),
            preserve_default=False,
        ),
    ]
