# Generated by Django 5.2.1 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_system', '0002_clients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.TextField(default=0, help_text='Plan description'),
            preserve_default=False,
        ),
    ]
