# Generated by Django 5.2.1 on 2025-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_system', '0004_rename_plan_id_clients_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.png', upload_to=''),
        ),
    ]
