# Generated by Django 5.2.1 on 2025-06-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_system', '0005_alter_clients_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='member',
            new_name='client',
        ),
    ]
