# Generated by Django 5.2.1 on 2025-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_system', '0006_rename_member_trainingsession_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
